constants.go, export_test.go, provisioning.go, provisioning_test.go, tpm.go, tpm_test.go
--- FAIL: TestProvisionWithInvalidEkCert (4.06s)
provisioning_test.go:561: ProvisionTPM should have returned an error
The intention of the test is for it to temporarily modify the template used for
creating the endorsement key, but this fails in go 1.10 because the template
exported to the test is a copy of the one that ProvisionTPM uses.
=> Fix TestProvisionWithInvalidEkCert failure

export_test.go, policy_test.go
This provides aliases of staticPolicyData and dynamicPolicyData, exported for testing, rather than the unnecessary structs that are currently exported.
=> Alias staticPolicyData and dynamicPolicyData in export_test.go

policy.go, policy_test.go, vendor/vendor.json
This will make it easier to generate authorization policies with more restrictive combinations of PCR values.
=> Execute a single TPM2_PolicyPCR command regardless of the number of PCRs

export_test.go, policy.go, policy_test.go, utils.go
TPM2_PolicyOR only supports 8 conditions, but merging all TPM2_PolicyPCR assertions in to a single assertion makes it more likely that we may generate compound authorization policies with more than 8 conditions in some more complex transient cases. This adds support for more than 8 conditions.
=> Support compound authorization policies with more than 8 conditions

constants.go, errors.go, export_test.go, keydata.go, pin.go, policy.go, policy_test.go, provisioning.go, provisioning_test.go, seal.go, seal_test.go, tpm_test.go, unseal.go, unseal_test.go
This adds SealKeyToTPM for creating a new sealed TPM object,
UpdateKeyPCRProtectionPolicy for making changes to the PCR protection
policy for an existing key, and SealedKeyObject.UnsealFromTPM for accessing
a secret sealed with SealKeyToTPM.
=> Add key sealing and unsealing APIs

sdefistub_policy.go, sdefistub_policy_test.go
The AddSystemdEFIStubProfile API enables the creation of a PCR policy that
seals a key to a permitted set of kernel commandlines when booting a
system using systemd's EFI stub loader.
=> Add AddSystemdEFIStubProfile API

export_test.go, policy.go, policy_test.go, unseal_test.go
This API is called to prevent access to any keys sealed by this package
until the next TPM restart or TPM reset. It works with any key sealed by
this package, regardless of the PCR protection policy.
=> Add LockAccessToSealedKeys API

crypt.go, crypt_test.go, errors.go, export_test.go, run-tests, secboot_test.go, tpm_test.go, vendor/vendor.json
This adds 2 functions for activating LUKS volumes.
ActivateVolumeWithTPMSealedKey attempts to activate a volume using the TPM
protected secret. If a PIN is required to unseal the secret, it will be
requested using systemd-ask-password. Once unsealed, the secret will be
used to activate the LUKS volume using systemd-cryptsetup.
ActivateVolumeWithTPMSealedKey can fall back to activating with the
fallback recovery key if activating with the TPM protected secret fails.
ActivateVolumeWithRecoveryKey can be used to activate a volume with the
fallback recovery key directly without attempting first with the TPM
protected secret.
In both functions, the fallback recovery key is requested using
systemd-ask-password. When activation with the recovery key is successful,
the key is added to the user …
=> Add ActivateVolume helper APIs for activating LUKS volumes

crypt_test.go, pin_test.go, policy_test.go, seal_test.go, secboot_test.go, tpm_test.go, unseal_test.go
Tests don't need cryptographically secure random numbers, so switch to
using math/rand in tests instead.
Fixes https://github.com/snapcore/secboot/issues/42
=> Don't use crypto/rand in tests

crypt_test.go, seal.go, seal_test.go, unseal_test.go
With AES-256 and XTS block cipher mode, both the volume key and derived
key (the one sealed by this function) are 512-bits.
=> Make SealKeyToTPM enforce a key size of 64-bytes

policy_test.go, sdefistub_policy_test.go, secboot_test.go, secureboot_policy_test.go, snapmodel_policy.go, snapmodel_policy_test.go, tpm_test.go, vendor/vendor.json
This binds a PCR profile to the brand (via the brand-id and sign-key-sha3-384 fields), model and series properties of a set of model assertions and defines the format in which snap-bootstrap should perform the actual measurement of these properties.
=> Add an API to bind a PCR profile to a set of snap models

policy.go
We were doing this to benefit from the integrity protections associated
with HMAC sessions, but some Infineon devices (specifically, the one in
the NUC7i5DNKE) don't permit sessions for TPM2_ReadClock, despite the
reference TPM implementation allowing them and the specification saying
that audit or encrypt sessions can be used.
=> Don't pass audit sessions to TPM2_ReadClock

tpm.go, tpm_test.go
If the TPM doesn't have a persistent endorsement key, both
ConnectToDefaultTPM and SecureConnectToDefaultTPM try to create a
transient one. RSA key creation on hardware TPMs is quite slow (in
excess of 10 seconds), so don't do this inside ConnectToDefaultTPM.
=> Don't create a transient EK in ConnectToDefaultTPM

export_test.go, keydata.go, pin.go, policy.go, policy_test.go, seal.go, unseal.go
This splits keyData, keyPolicyUpdateData, staticPolicyData and
dynamicPolicyData in to version agnostic parts and version-specific
parts. The version-specific parts are what is marshalled / unmarshalled.
=> Make it easier to bump the metadata version

export_test.go, pcr_profile.go
AddEFISecureBootPolicyProfile currently operates non-recursively. A
future PR will change the interaction between
AddEFISecureBootPolicyProfile and PCRProtectionProfile so that it
creates a profile using the methods of PCRProtectionProfile rather
than computing PCR values itself and adding them to the profile with
PCRProtectionProfile.AddPCRValue as it does now. This change will
preserve the property that computing a PCR profile for the secure
boot policy is non-recursive.
=> Make PCRProtectionProfile.computePCRValues non recursive

seal.go, seal_test.go
Fixes https://github.com/snapcore/secboot/issues/26
=> Make SealKeyToTPM reject a PCRProtectionProfile with unsupported PCRs

secureboot_policy.go, secureboot_policy_test.go
AddEFISecureBootPolicyProfile computes the wrong PCR profile for a
load sequence that isn't bootable because the unbootable property isn't
preserved across branches.
=> Don't generate incorrect profiles for PCR7 in some cases

pcr_profile.go, pcr_profile_test.go
Calling PCRProtectionProfile.AddProfileOR with no branches is pointless,
but it probably shouldn't result in a panic when computing PCR digests.
Handle this case gracefully by just omitting it from the profile.
=> Don't panic when processing a profile with an empty branch

tpm_test.go
This creates a temporary directory for storing the TPM simulator's
persistent data. For the snap version of the TPM simulator, it uses the
snap's common data directory instead, because it has a private tmpdir in
which we can't create a temporary directory outside of the snap.
Once this code moves in internal/testutil, it will have the ability to
specify a location for the persistent data, so that the simulator can run
with pre-generated, checked-in data.
=> Store the TPM simulator's persistent data in a temporary directory

internal/tcg/tcg.go, keydata.go, keydata_test.go, provisioning_test.go, tpm_test.go
Fixes https://github.com/snapcore/secboot/issues/53
=> Fix for validateKeyData when sealed key access is locked

export_test.go, secureboot_policy.go, secureboot_policy_test.go
This simplifies identifyInitialOSLaunchVerificationEvent and also ensures
it should work with UEFI system preparation applications.
=> Simplify identifyInitialOSLaunchVerificationEvent

export_test.go, keydata.go, pin.go, pin_test.go, policy.go, policy_test.go, seal.go, utils.go
We create 1 signing key during provisioning, and 2 during sealing. EC keys are a bit faster to create than RSA ones, so switch from RSA-PSS to ECDSA where we sign digests that have to be verified by the TPM.
=> Switch from RSA-PSS to ECDSA for signing keys

efi.go, efibootmanager_policy.go, vendor/vendor.json
make the EFIImage interface follow that as well
=> Switch to use Container.RandomAccessFile's result Size

keydata.go, policy.go, policy_test.go, seal.go, tpm.go, utils.go, vendor/vendor.json
This simplifies the CustomMarshaller interface so that implementations
don't need to keep track of the number of bytes read or written.
=> Update the vendored version of go-tpm2

crypt_test.go, export_test.go, internal/compattest/compattest_test.go, keydata.go, keydata_test.go, pin.go, pin_test.go, policy.go, policy_test.go, seal.go, seal_test.go, secboot_test.go, tools/gen-compattest-data/main.go, unseal.go, unseal_test.go, vendor/vendor.json
The current implementation uses a NV index for PIN integration using
the TPM2_PolicySecret assertion. In the original technical plan, PIN
integration was going to be achieved using a separate TPM object (and
TPM2_PolicySecret), although this was changed to a NV index instead.
There are a couple of reasons for this approach:
- The original plan didn't feature the use of the TPM2_PolicyAuthorize
assertion for allowing the PCR policy to be updated without having to
reseal - instead, updating the PCR policy was going to be achieved by
resealing (ie, creating a new sealed key object). Having a separate
object for PIN integration avoids the need to know the PIN in order to
perform a resealing operation.
- I initially thought that the sealed key object containing the disk
encryption key required …
=> Don't use a NV index for PIN integration

crypt.go, crypt_test.go, errors.go, export_test.go, internal/compattest/compattest_test.go, internal/compattest/v0_test.go, keydata.go, keydata_test.go, pin.go, pin_test.go, policy.go, policy_test.go, seal.go, seal_test.go, tools/gen-compattest-data/main.go, unseal.go, unseal_test.go, utils.go
Now that an elliptic curve key is used to authorize PCR policy updates and
this is significantly smaller than the previous RSA key, store the private
part of the key inside the sealed key object and have it returned from
SealedKeyObject.UnsealFromTPM rather than storing it inside a file inside
the encrypted volume.
This removes the need to store an additional file in order to use
UpdateKeyPCRProtectionPolicy.
ActivateVolumeWithTPMSealedKey now adds the private part of the key to
the root user's keyring. Callers to UpdateKeyPCRProtectionPolicy will
need to retrieve the key data from there using the keyctl syscall.
=> Store the private part of the policy auth key inside the sealed key object

crypt.go, crypt_test.go, errors.go, keydata_test.go, pin_test.go, provisioning.go, provisioning_test.go, seal_test.go, tools/gen-compattest-data/main.go, tpm_test.go, unseal_test.go
ProvisionStatus is a problematic API - AttrValidSRK and AttrValidEK
indicate that objects with the expected public areas exist at the expected
handles, but can't indicate whether those objects were created with the
correct templates and are actually valid objects. These attributes can't
be used to make a decision about whether ProvisionTPM should be called or
not, so just remove the ProvisionStatus API entirely.
Rename ProvisionTPM to EnsureProvisioned (and make it a method of
TPMConnection), and introduce a new error (ErrTPMProvisioningRequiresLockout)
which is returned from EnsureProvisioned if it is called with
ProvisionModeWithoutLockout but use of the lockout hierarchy is required
to fully provision the TPM. This new error is an indication that
EnsureProvisioned needs to be called …
=> Remove ProvisionStatus and refactor provision API

crypt.go, crypt_test.go
Also rename PIN in its definition to Passphrase to move toward
better and also more abstract naming.
Same in the corresponding RecoveryKeyUsageReason code.
See also issue #113
=> Have a single ActivateVolumeOptions struct for the ActivateVolumeWith* family

constants.go, crypt_test.go, export_test.go, internal/compattest/v0_test.go, keydata.go, pin_test.go, policy.go, policy_test.go, provisioning.go, provisioning_test.go, seal.go, seal_test.go, unseal.go, unseal_test.go
Access to sealed keys can be denied until the next TPM reset or restart
by calling LockAccessToSealedKeys. The traditional way of achieving this
is by extending another value to a PCR that is included in the PCR
selection for a sealed key's authorization policy after the key has been
unsealed, which makes its authorization policy non-satisfiable until the
next reset or restart. The issue with this is that it makes the feature
dependent on the PCR profile.
The current implementation of LockAccessToSealedKeys uses a NV index at a
well known handle and takes advantage of a couple of properties of NV
index read locks:
- Once enabled, they can only be disabled by a TPM reset or restart.
- Enabling a read lock sets the index's TPMA_NV_READLOCKED attribute which
changes its name.
Sealed keys …
=> Reimplement the support for LockAccessToSealedKeys to reduce fragility

seal.go, seal_test.go, secboot_test.go, unseal_test.go
This introduces the ability to create keys that are related and share
authorization policies, by adding a new RelatedSealedKey field to
KeyCreationParams. If this is initialized to an existing key, then
SealKeyToTPM will seal a new key with an identical authorization
policy after performing validation on the original key data, as
opposed to computing a new authorization policy. Keys that share a
policy also share a PCR policy counter, if one is defined.
This also requires the private part of the signing key for authorizing
policy updates in the form returned by SealKeyToTPM and UnsealFromTPM
(so that it can be included in the new sealed key object), which is
provided by another new field in KeyCreationParams (RelatedAuthKey).
I'm not sure of the naming yet - "related" is probably the best …
=> Add the ability to seal keys with shared authorization policies

internal/testutil/io.go, seal.go, seal_test.go
This introduces UpdateKeyPCRProtectionPolicyMultiple, which can update the
PCR policy for multiple related keys (those that share an identical
authorization policy).
Note that the new API follows the style of the existing API (which accepts
file paths) - I'd prefer to change this in the future so that the actual
decoded SealedKeyObject is passed to these instead.
This also adds some simple tests for UpdateKeyPCRProtectionPolicy,
which were entirely missing previously.
=> Add UpdateKeyPCRProtectionPolicyMultiple

crypt.go, crypt_test.go
Add a helper for activating a volume with an explicitly provided key.
=> Add helper for activating a LUKS2 volume with explicitly provided key

crypt.go, crypt_test.go
Support passing --luks2-keyslots-size and --luks2-metadata-size to cryptsetup
when creating a LUKS2 container.
=> Support setting LUKS2 metadata and keyslots area sizes when creating containers

crypt.go, crypt_test.go, errors.go
This adds the ability to activate a volume with multiple TPM sealed key objects. The existing API is not just a wrapper around the new API.
I'm not sure what to do about returning errors from this function - I've added a new ActivateWithMultipleTPMSealedKeysError which has the ability to access each of the individual errors, but I'm not sure that it's actually worth surfacing all of this information.
I've renamed RecoveryKeyUsageReason to KeyErrorCode, as its usage is now more associated with why a key failed rather than why the recovery key was used. Where multiple keys are supplied and they all fail, they each have their own error code.
=> Add ActivateVolumeWithMultipleTPMSealedKeys

crypt.go, crypt_test.go
This updates the KDF parameters for the primary key to not
hardcode minimum values for iterations and memory cost, and instead
specify a benchmark time of 200ms.
=> Update the KDF parameters for the primary key

efi.go
This was only used in the fmt.Stringer implementation. Instead, just
format details of the supplied snap.Container.
=> Remove SnapFileEFIImage.Path

crypt.go, crypt_test.go, crypt_tpm.go, crypt_tpm_test.go
This functionality is unused in snapd at the moment, and the current
implementation works differently to the latest design document - it uses
the key description to pass error status, but error status from the
early boot environment will be preserved differently in a future PR.
As the current functionality is usused, there's no need to support the
current implementation for backwards compatibility reasons, and so it's
going to be easier to just delete this code for now and add bits back
later as required.
=> Remove GetActivationDataFromKernel and related code

internal/testutil/checkers.go, internal/testutil/checkers_test.go, internal/testutil/testutil_test.go, keydata.go, keydata_file.go, keydata_file_test.go, keydata_test.go, platform.go, snap.go, snap_test.go, snapmodel_policy.go, snapmodel_policy_test.go, vendor/vendor.json
This adds an initial implementation of a platform-agnostic key API.
Several new types are added:
- KeyData, which is the main representation of a key.
- KeyDataReader, which is the interface that KeyData uses to read
key data from persistent storage.
- KeyDataWriter, which is the interface that KeyData uses to write
key data to persistent storage.
- KeyCreationData, which contains the information required to create
a new KeyData.
- KeyPayload, which represents the data protected by a KeyData object.
- PlatformKeyData, which represents the data exchanged between this
package and platform implementations.
- PlatformKeyDataHandler, which is the interface used by this package
to communicate with platform implementations.
Key data is stored in JSON.
The new API contains a mechanism to bind the …
=> Add platform agnostic keydata

crypt_test.go, crypt_tpm_test.go
Also use a 32-bit rather than 64-bit key size during tests, as
this matches the real world.
=> Use the correct recovery key type in crypt_test.go

crypt_test.go, crypt_tpm_test.go
Instead, create them as they are needed by individual tests. In a
future PR, some tests will use different mock key configurations,
and this will just make it a bit simpler.
This is based on https://github.com/snapcore/secboot/pull/135
=> Remove recoveryKey and primaryKey from cryptSuite

crypt.go, crypt_test.go, keydata.go, keydata_file.go, keydata_file_test.go, keydata_test.go
Rather than expecting the consumer of the API to supply a key
name which is used to create a KeyID, and rather than storing an
ID inside the KeyData, just make the KeyID automatically generated,
completely unique and make KeyData.ID always return a fresh value.
=> Automatically create a KeyID and make it genuinely unique

crypt.go, crypt_test.go, crypt_tpm.go, crypt_tpm_test.go, keyring.go
This is currently unused by snapd.
The field is problematic because it exposes all of systemd-cryptsetup's
options, many of which are incompatible with how we use it in secboot.
If there is a genuine need in the future to expose some extra options,
this can be done with a more explicit API instead.
This also makes it slightly easier to move the TPM code out of the
core secboot package because it's not necessary to duplicate
makeActivateOptions or move it to an internal package.
=> Remove ActivateOptions field from ActivateVolumeOptions

crypt_tpm.go, crypt_tpm_test.go, export_test.go, provisioning.go, provisioning_test.go, seal.go, seal_test.go
TPMConnection.EnsureProvisioned will create and persist a storage
primary key as described in the "TCG TPM v2.0 Provisioning Guidance"
specification (https://trustedcomputinggroup.org/wp-content/uploads/TCG-TPM-v2.0-Provisioning-Guidance-Published-v1r1.pdf).
This specification says that the unique field of the storage primary
key template should be 256 bytes of zeroes, which is the same as the
endorsement key template.
However, many existing tools (including tpm2-tools) define the template
for the storage primary key with an empty unique field, and this creates
a different primary key. This is a deviation from the TCG specifications.
Whilst this isn't a problem for Ubuntu Core, it may be a problem on
systems where the initial encryption and key protection happens before
first boot, and …
=> Support provisioning the TPM with a custom SRK

keydata_tpm.go, seal.go, seal_test.go, unseal_test.go
This allows a key to be protected by an arbitrary TPM key without
access to the actual TPM. The key will be protected by a duplication
object that has to be imported into the target TPM before it is used.
Note that this doesn't yet include an API to persist the imported object,
although unsealing works ok as it imports the object automatically.
The imported object will be persisted automatically on the first modification
to the key data.
=> Add SealKeyToExternalTPMStorageKey API

crypt.go, crypt_test.go, crypt_tpm.go, crypt_tpm_test.go, export_test.go, internal/luks2/activate.go, internal/luks2/activate_test.go, internal/luks2/cryptsetup.go, internal/luks2/cryptsetup_test.go, internal/luks2/export_test.go, internal/luks2/fifo.go, internal/luks2/luks2.go, internal/luks2/luks2test/luks2test.go, internal/luks2/metadata.go, internal/luks2/metadata_test.go, internal/paths/paths.go, internal/paths/pathstest/pathstest.go, run-tests
This ports crypt.go to use internal/luks2, with no other changes yet.
I've kept the original tests that use a mocked cryptsetup, but added
some additional tests that use a real cryptsetup. As these take a while
to run, I've added a --no-expensive-cryptsetup-tests option to run-tests
which skips the new tests (and the cryptsetup tests in internal/luks2).
This just passes an option in via the environment to avoid having to
parse a new argument in every test binary, and to avoid splitting the
single call to go test.
The existing API needs to be able to use the luksAddKey command
with the --key-slot option which internal/luks2 didn't support, so I've
added that too.
=> Use internal luks2 package

.github/workflows/test.yaml, keyring_test.go
Some tests that touch the keyring are failing since the switch
to github actions. There is a check in other suites to skip
keyring tests in environments that are unsuitable, but not in
the tests that are failing. This adds that check there too.
(We need to figure out how to make these tests work in
github actions, so this is a temporary fix for now just to
get the tests to pass).
Note that I also changed the go version to 1.9 (from 1.10)
when switching to github actions because that was the
minimum required by snapd, but that makes go vet fail.
I've changed the go version to 1.13 now that is the
minimum required by snapd.
=> Ensure keyring tests are skipped in unsuitable environments

internal/compattest/compattest_test.go, internal/compattest/v0_test.go, internal/compattest/v1_test.go, tpm2/crypt_test.go, tpm2/export_test.go, tpm2/keydata.go, tpm2/pin.go, tpm2/pin_test.go, tpm2/seal.go, tpm2/seal_test.go, tpm2/unseal.go, tpm2/unseal_test.go
SealedKeyObject was originally intended to provide some read-only interaction with a sealed key file to avoid having to decode it more than once. There are some additional functions in the global namespace that modify a keyfile (ChangePIN and UpdateKeyPCRProtectionPolicy).
In order to create a tpm2 KeyData platform implementation, the functions that interact with TPM sealed keys need to be updated to work with bytes without having to care about how the bytes are stored. The current functions have a hard dependency on file storage because file paths are exposed via the APIs.
As a prerequisite to removing the hard dependency on file storage, the existing global functions that modify a keyfile should be converted to methods of SealedKeyObject. Future PRs will then work towards removing the …
=> Move some functions to SealedKeyObject

crypt.go, internal/luks2/cryptsetup.go, internal/luks2/cryptsetup_test.go, tpm2/crypt_test.go
This ports part of https://github.com/snapcore/secboot/pull/164 to
the internal/luks2 package. There will be a follow up to expose
this via the public APIs, but I've got some other changes planned
for those as well.
=> internal/luks2: Add KDFOptions for Format and AddKey

crypt.go, crypt_test.go
This ports https://github.com/snapcore/secboot/pull/164 to master.
As with the code that landed previously, there are no new tests for
the additional functionality yet. I've got some other work in progress
that touches these APIs and that work will incorporate the appropriate
tests.
=> crypt: add KDF options to API

internal/compattest/compattest_test.go, internal/compattest/v0_test.go, internal/compattest/v1_test.go, tpm2/crypt.go, tpm2/crypt_test.go, tpm2/errors.go, tpm2/export_test.go, tpm2/keydata.go, tpm2/keydata_test.go, tpm2/seal.go, tpm2/seal_test.go, tpm2/tpm2_test.go, tpm2/unseal.go, tpm2/unseal_test.go
In order to create a tpm2 platform implementation for KeyData,
SealedKeyObject needs to be storage agnostic instead of having
a hard dependency on file paths.
This makes ReadSealedKeyObject take an io.Reader.
SealedKeyObject.UpdatePCRProtectionPolicy now only modifies the
in-memory SealedKeyObject. SealedKeyObject.WriteAtomic has been
introduced for persisting changes to some storage mechanism.
Two additional APIs have been introduced to work with existing
sealed key files - ReadSealedKeyObjectFromFile and
NewFileSealedKeyObjectWriter.
Existing sealed key files use a AF-splitter. This has limited use
on solid state drives and was introduced to make PIN changes more
secure with key data that is stored inside a filesystem. For that
reason, the generic ReadSealedKeyObject and …
=> tpm2: Make ReadSealedKeyObject take a io.Reader

tpm2/export_test.go, tpm2/keydata.go, tpm2/seal.go, tpm2/unseal.go
The internal keyData struct has a bunch of methods because
once-upon-a-time, SealedKeyObject was only created for unsealing
and we only created keyData internall for other operations.
Now that's SealedKeyObject is used for everything, just make the
methods of keyData unexported methods of SealedKeyObject, as the
current split appears to be completely arbitrary now.
=> tpm2: remove methods from keyData

internal/compattest/v0_test.go, internal/compattest/v1_test.go, tpm2/export_test.go, tpm2/keydata_v0_test.go, tpm2/keydata_v1_test.go, tpm2/keydata_v2_test.go, tpm2/platform_legacy_test.go, tpm2/policy.go, tpm2/policy_test.go, tpm2/policy_v0.go, tpm2/policy_v0_test.go, tpm2/policy_v1.go, tpm2/seal_test.go, tpm2/unseal_test.go
This splits the tree structure used for executing PolicyOR assertions
into 2 - there is the existing "flattened" tree on-disk representation,
but this is now converted to an actual tree structure.
=> tpm2: split the tree used for PolicyOR assertions

auth_requestor.go, auth_requestor_systemd.go, auth_requestor_systemd_test.go, crypt.go, crypt_test.go
This adds an AuthRequestor interface that is used by the Activate*
APIs to request a credential (passphrase or recovery key) via some
agent.
It also adds an implementation of AuthRequestor that uses
systemd-ask-password. The new API provides a simple template based
way to define the message that is displayed.
=> Add AuthRequestor interface

crypt.go, crypt_test.go, internal/luks2/cryptsetup.go, internal/luks2/cryptsetup_test.go, internal/luks2/internal/luks2.go, internal/luks2/luks2test/luks2test.go
We depend on some cryptsetup features that aren't in all of the
cryptsetup versions we have in Ubuntu, so add a simple internal
feature detection API for those. This is motivated by the fact
that we're going to depend on --token-replace, which has just been
approved to land upstream and which we'll need to backport.
=> luks2: add DetectCryptsetupFeatures

crypt.go, crypt_test.go
The ActivateVolumeWith*KeyData functions currently return a
SnapModelChecker to delegate authorization of the Snap model to
snap-bootstrap. This means that authorization of the model is
performed after activation of the container. There are a couple
of issues with this though:
- If multiple KeyData are supplied and the container is activated
with one of these but the model isn't authorized, it requires another
call to ActivateVolumeWithMultipleKeyData in order to try others.
- If the model isn't auhtorized with any KeyData, the container has
to be deactivated again.
The first issue is difficult to solve with the current architecture
when KeyData are loaded from the LUKS metadata rather than being
supplied externally from a file.
This implements a different approach where SnapModelChecker …
=> move Snap model authorization to ActivateVolumeWith*KeyData

internal/compattest/compattest_test.go, tpm2/export_test.go, tpm2/keydata.go, tpm2/platform_legacy.go, tpm2/policy.go, tpm2/policy_v0.go, tpm2/policy_v1.go, tpm2/seal.go, tpm2/seal_test.go, tpm2/unseal.go, tpm2/unseal_test.go
This removes the PolicyAuthKey type and aligns the
tpm2 code with the platform agnostic code, in preparation
for adding a proper tpm2 platform.
=> tpm2: use DiskUnlockKey and AuxiliaryKey types

keydata.go, keydata_test.go, platform.go, tpm2/platform_legacy.go
This aligns the representation of the platform handle in KeyCreationData
with the representation introduced to the KeyData API in
https://github.com/snapcore/secboot/pull/191.
Note that the representation of the platform handle in PlatformKeyDataHandler
remains unchanged (it is the encoded JSON). This is becuase
PlatformKeyDataHandler is used to call from KeyData to an implementation,
and it is not possible to decode the JSON in this scenario because the
data is opaque.
=> Allow the platform handle to be any arbitrary JSON value in KeyCreationData

internal/luksview/export_test.go, internal/luksview/luksview_test.go, internal/luksview/tokens.go, internal/luksview/tokens_test.go, internal/luksview/view.go, internal/luksview/view_test.go
This adds a new package containing a view of the LUKS2 metadata
in a way that is most useful to secboot.
It also contains a representation of tokens that will be used by
secboot. Each token has a name, which is an arbitrary string used to
identify its associated keyslot. The name is intended to be unique
between keyslots and secboot will enforce this. All tokens created by
secboot will have a name and will be associated with one keyslot.
Tokens without a name or which are associated by more than one keyslot
are ignored by the View API.
For context, here's some notes about how the View API is intended to be
used:
- View.TokenByName returns the token for the keyslot with the
supplied name, and is intended to be used when performing changes to
the slot (eg, updating the PCR policy in the TPM …
=> Add internal/luksview package

tpm2/policy_test.go
These tests currently only run if there's a TPM, but they don't
need one.
=> tpm2: tests for newKeyDataPolicy don't require a TPM

crypt.go, crypt_test.go, internal/luks2/cryptsetup.go, internal/luks2/cryptsetup_test.go, internal/luks2/export_test.go
luks2.Format already returns an error if a custom metadata area
or keyslot area size is specified but cryptsetup doesn't support
these options, but secboot.InitializeLUKS2Container performs its
own checking of these parameters. This just moves them into the
same place.
=> luks2: Move format argument validation to luks2 package

crypt.go, crypt_test.go, export_test.go
Snapd is already tuning the KDF cost parameters to their minimum,
so just use these defaults in secboot.
=> update LUKS2 KDF defaults to match snapd

crypt.go, keydata_test.go, snap.go, tpm2/snapmodel_policy.go, tpm2/snapmodel_policy_test.go, vendor/vendor.json
The simplest approach seemed to be to integrate that info as a high
bit in the grade code, for clarity snapd can grow an internal constant
as well to reserve this.
I moved snapd only partially forward because go-tpm2/testutil needs
fixing first, the signature of UserCommonDataDir has changed,
eventually that code will need to consider two possible directories.
=> Support measuring extended classic models with a distinct hash

crypt.go, crypt_test.go, keydata_luks.go, keydata_luks_test.go, keydata_test.go
This adds support for reading and writing KeyData objects to the LUKS
header. A follow up PR will add support for making use of these during
activation.
=> Add KeyDataReader and KeyDataWriter implementations for LUKS

keydata.go, keydata_test.go, vendor/vendor.json
The current implementation uses a DRBG where a simpler KDF would be more appropriate. DRBGs provide some additional features that are just not required here, which are intended to protect prior and future random numbers generated from the same source. All of the extra keys derived from the recovered key payload are all used for protection of the same resource.
HKDF is a core part of the TLS1.3 key schedule. Using this rather than a module we've developed is probably going to make future FIPS 140-3 efforts quite a bit easier given that the go standard library already makes use of it internally (the version it vendors will most likely require openssl integration which we could just copy for external use)
This maintains backwards compatibility with existing keys, with a test to ensure that …
=> keydata: use HKDF to derive the snap model HMAC key

internal/compattest/compattest_test.go, internal/testutil/checkers.go, internal/testutil/checkers_test.go, tools/gen-compattest-data/main.go, tpm2/keydata_v0_test.go, tpm2/keydata_v1_test.go, tpm2/keydata_v2_test.go, tpm2/pcr_profile.go, tpm2/pcr_profile_test.go, tpm2/policy.go, tpm2/policy_test.go, tpm2/policy_v0.go, tpm2/policy_v0_test.go, tpm2/policy_v1.go, tpm2/policy_v1_test.go, tpm2/provisioning_test.go, tpm2/seal_legacy_test.go, tpm2/snapmodel_policy.go, tpm2/tpm_test.go, tpm2/unseal_legacy_test.go, tpm2/update_legacy_test.go, tpm2/update_test.go, vendor/vendor.json
This includes a hardening fix for data that is deserialized from disk (see https://github.com/canonical/go-tpm2/commit/1a80c4b47c2b8f0e7a013b4ff5df27d331c48548).
There are some other changes, mostly removal of some checkers from the testutil package because they aren't TPM-specific and don't really belong there.
This adds a few things I want to use in secboot.
=> tpm2: update go-tpm2 dependency

efi/secureboot_policy.go, vendor/vendor.json
This was originally needed for work on Azure, which has been using a fork of secboot.
I'm updating it now to the latest tagged release of go-efilib, which has some
additional enhancements now (particularly, more useful WIN_CERTIFICATE
types that are useful in efi/secureboot_policy.go)
=> efi: update to latest go-efilib

tpm2/tpm.go, tpm2/tpm_test.go
This is a backport of https://github.com/snapcore/secboot/pull/220/files to the uc22 branch so that it can be consumed by snapd.
=> Backport PR#220 to uc22

tpm2/pcr_profile.go, tpm2/pcr_profile_test.go, tpm2/seal_legacy_test.go
A profile that has AddPCRValueFromTPM called multiple times executes
a TPM2_PCR_Read command for each addition. This is unnecessary as
multiple values can be fetched in a single command.
Reduce this to a minimal sequence of commands by calling
TPMContext.PCRRead once and having go-tpm2 fetch all of the values
in the smallest number of commands possible.
=> tpm2: Squash TPM2_PCR_Read commands

tpm2/pcr_profile.go, tpm2/pcr_profile_test.go
This doesn't affect generated policy, but does improve the readability
of profiles when printed as a string for debugging purposes - especially
given our fairly liberal use of branches in order to simplify profile
construction.
=> tpm2: elide empty branch points or those with only a single sub-branch

argon2_test.go, crypt_test.go, internal/testutil/kdf.go, keydata_test.go
This moves the mock KDF implementation in secboot_test to
internal/testutil, as it's going to be used inside the tpm2 package in a
follow up PR.
=> internal/testutil: Add MockKDF

keydata.go, keydata_test.go
https://github.com/snapcore/secboot/pull/217 introduced HKDF to derive a
HMAC key. The TPM code is going to use HKDF to derive an elliptic
curve key from the same input key. When working on the latter one and
wondering whether to generate another salt for this, I realized that we
only need to perform the expand step of HKDF. The code I introduced is
currently performing both the extract and expand steps.
From the RFC (https://www.rfc-editor.org/rfc/rfc5869):
> In many applications, the input keying material is not necessarily
> distributed uniformly, and the attacker may have some partial
> knowledge about it (for example, a Diffie-Hellman value computed by a
> key exchange protocol) or even partial control of it (as in some
> entropy-gathering applications).  Thus, the goal of the …
=> Only use the expand part of HKDF

keydata.go, keydata_luks_test.go, keydata_test.go, tpm2/platform_legacy.go
"Creation data" is a bit of an overloaded term when using a TPM, because it specifically refers to data that can be used to prove the creation environment of a TPM object. I'm going to add support to the tpm2 package for saving the creation data to facilitate subsequent attestation of the state of the initial install environment, so rename this struct to avoid confusion.
The PR I've proposed to add a new ProtectKeyWithTPM API (https://github.com/snapcore/secboot/pull/202) also uses "params" in this context, so it's consistent with that.
=> Rename KeyCreationData to KeyCreationParams

crypt.go, internal/luks2/cryptsetup.go, internal/luks2/cryptsetup_test.go
Adding support for InlineCryptoEngine flag.
This is passed to `cryptsetup` as an additional `--inline-crypto-engine` flag.
This requires a modified `cryptsetup` supporting `inline-crypto-engine` feature.
=> cryptsetup: add support for ICE flag

keydata.go
The passphrase derived encryption key size is stored in the key data when a passphrase is set but is then not used consistently after that. It's used to calculate the length of key material to derive from the passphrase, but then the compiled in constant key length is used to index into the returned bytes in order to separate the encryption key from the IV. This will cause a panic if the saved key data is modified to reduce the value of the key size.
This also renames the passphraseDerivdKeyLen constant - it's not the correct description as the actual derived key length is one block size larger than this.
=> keydata: Use the saved key size consistently when using a passphrase

tpm2/export_test.go, tpm2/key_sealer.go, tpm2/key_sealer_test.go
This is a new internal interface that is going to be used by the new key
sealing APIs in order to increase code use between them.
=> tpm2: add internal key sealer interface

efi/bootmanager_policy.go, efi/bootmanager_policy_test.go, efi/sdstub_policy.go, efi/sdstub_policy_test.go, tools/gen-compattest-data/main.go, tpm2/snapmodel_policy.go, tpm2/snapmodel_policy_test.go
This updates most code (with the exception of efi/secureboot_policy.go)
to make use of the newer PCRProtectionProfile APIs.
=> efi,tpm2: Make use of updated PCRProtectionProfile APIs

tpm2/export_test.go, tpm2/keydata.go, tpm2/keydata_test.go, tpm2/seal_legacy.go
In order to support the ability to add additional keys to an existing
system in the future, newKeyData must be able to return a keyData
implementation that has the same metadata version as the supplied
keyDataPolicy implementation - this may not always be the latest
version.
=> tpm2: Make newKeyData support multiple metadata versions

efi/bootmanager_policy.go, efi/bootmanager_policy_test.go, efi/efi.go, efi/export_test.go, efi/image.go, efi/image_test.go, efi/secureboot_policy.go, efi/secureboot_policy_test.go, tools/gen-compattest-data/main.go
This is the start of a series of changes that significantly refactor the code in the efi package. These changes will:
- Make the code more modular and maintainable.
- Add support for applying secure boot revocations, including updating shim.
- Replace the existing AddSecureBootPolicyProfile and AddBootManagerCodeProfile APIs with a single API that will add an entire profile. This will also replace the need to use the existing AddSystemdStubProfile and tpm2.AddSnapModelProfile APIs.
This last one requires the ability to specify external parameters that are not part of an executable binary, which is partly what this PR adds. Note that this does add some APIs that aren't used yet. It also implements ImageLoadEventSource as one of these new parameters, which is a bit strange - this is …
=> efi: updates to ImageLoadEvent

efi/export_test.go, efi/secureboot_policy.go, efi/secureboot_policy_test.go
So `$Version: 15 $` is fine in the .data.ident section.
=> efi: allow the case of minor version not present

.github/workflows/test.yaml, efi/secureboot.go, vendor/vendor.json
This addresses an issue where some valid signed variable update
payloads could fail to parse correctly because although the UEFI
spec permits signatures with the PKCS#7 SignedData wrapped in an
optional outer ContentInfo structure, go-efilib didn't recognize
signatures in the wrapped case. I discovered this when creating
mock signatures for unit tests in secboot.
This also bumps secboot's go requirement to 1.18 to match snapd,
as go-efilib is pulling in the latest version of x/cryptobyte which
has dependencies that require this as well now.
=> Update github.com/canonical/go-efilib dependency

internal/luks2/cryptsetup.go, internal/luks2/cryptsetup_test.go, internal/luks2/export_test.go
Most hardware should use aes-xts-plain64 for LUKS2 but on 32bit arm the XTS mode cannot be accelerated by the hardware which leads to very poor perfomance (less than half compared to cbc mode). Therefore this commit switches the default on 32bit ARM to aes-cbc-essiv:sha256.
Note that this is a simple approach, we could run "cryptsetup benchmark" but that seems over engineered (and easy enough to switch if we need in the future).
=> luks2: use "aes-cbc-essiv:sha256" on 32bit arm HW

internal/luks2/cryptsetup.go, internal/luks2/cryptsetup_test.go, internal/luks2/export_test.go
This is a backport of the aes-cbc selection on arm (https://github.com/snapcore/secboot/pull/252) to the uc22 branch.
=> luks2: use "aes-cbc-essiv:sha256" on 32bit arm HW (uc22)

tpm2/export_test.go, tpm2/keydata.go, tpm2/keydata_legacy.go, tpm2/platform.go, tpm2/platform_test.go, tpm2/policy.go, tpm2/policy_v3.go, tpm2/seal.go, tpm2/seal_legacy.go, tpm2/seal_test.go, tpm2/unseal_legacy.go, tpm2/update.go, tpm2/update_legacy.go, tpm2/update_test.go
This adds an initial TPM2 implementation of PlatformKeyDataHandler, plus
new APIs for sealing keys to make use of secboot.KeyData.
The new sealing APIs are ProtectKeyWithTPM, ProtectKeysWithTPM and
ProtectKeyWithExternalStorageKey, to replace the SealKeyToTPM,
SealKeyToTPMMultiple and SealKeyToExternalTPMStorageKey. They are
implemented in a way to facilitate adding another API in the future to
protect additional keys using the same policy as an existing key.
Also added is a new API to update the PCR policy for multiple keys in
one go - UpdateKeyDataPCRProtectionPolicy, which replaces
UpdateKeyPCRProtectionPolicyMultiple.
Obtaining a SealedKeyObject data structure associated with a key is done
differently for keys created with the new APIs. There is a new API to
decode a SealedKeyObject …
=> tpm2: Add initial PlatformKeyDataHandler implementation

.github/workflows/test.yaml, internal/crypto/crypto_test.go, internal/crypto/ecdsa.go, internal/crypto/ecdsa_1_19_test.go, internal/crypto/ecdsa_test.go, tpm2/policy_v3.go
go 1.20 changed the behaviour of ecdsa.GenerateKey so that it no longer produces the same key given the same sequence of random bytes, and so that it is no longer even deterministic.
Work around this by reimplementing the ECDSA key generation based on FIPS186-4 section B.4.1.
=> tpm2: implement deterministic ECDSA key generation

go.mod, go.sum
This moves to the latest version of tcglog-parser which has the the downgraded godbus dependency.
=> go.mod: upgrade tcglog-parser revision

efi/efi_test.go, efi/image_rules_defs.go
Grub's module section has the name "mods" rather than ".mods"
=> efi: Fix a potential grub matching bug

crypt.go, crypt_test.go, export_test.go, internal/luks2/cryptsetup.go, internal/luks2/cryptsetup_test.go, internal/luksview/tokens_test.go, internal/luksview/view_test.go
We currently don't run luksKillSlot in batch mode, which means that
we need to supply an existing key in order to delete a keyslot.
Cryptsetup requires this to be for another keyslot unless the last
keyslot is being deleted, so it doesn't provide any protections to
prevent deletion of the last keyslot. It is intended to ensure that
a user who deletes a keyslot still knows a passphrase for another
keyslot.
The fdemanager service will have an endpoint to delete a keyslot, but
the API does not require an unlock key because unlock keys aren't
something users will generally interact with. In this case, the service
will grab the key used to unlock the device on the current boot from
the kernel and pass this to secboot, so not running luksKillSlot in
batch mode actually doesn't offer any safety …
=> luks2: run luksKillSlot in batch mode

crypt_test.go, internal/luks2/cryptsetup_test.go
There are a few tests where we time the KDF operation because there
isn't another way to determine if it was configured correctly by
cryptsetup. These tests have always been a little bit flaky, and they
have been significantly more so recently.
Stop timing them, and instead:
- in internal/luks2, just rely on the fact that we verify the expected
commandline arguments were passed to cryptsetup. We have to assume
that these options are correct, which is what the existing tests
attempted to confirm.
- in crypt_test.go, ensure that we pass the correct target time to
internal/luks2.
=> luks2: don't time tests to verify KDF settings

go.mod, go.sum
This pulls in https://github.com/canonical/go-efilib/pull/12 to workaround how secboot uses the
WinCertificateAuthenticode.CertLikelyTrustAnchor API.
=> update go-efilib to v0.9.5

go.mod, go.sum, internal/tpm2test/tcti.go, tpm2/tpm_test.go
This includes a few changes that may be used in secboot in future PRs:
- some new helpers for working with objects and constructing templates (package objectutil).
- new APIs for constructing, serializing and executing authorization policies (package policyutil).
- a new API for interacting with the physical presence interface (package ppi).
- a TPMDevice interface and an API for enumerating and opening devices and using the resource manager device.
- deprecated the existing util, templates and crypto packages, as this functionality moved elsewhere.
=> Update go-tpm2 to v1.1.0

go.mod, go.sum, internal/tpm2test/tcti.go, tpm2/tpm_test.go
This pulls in a fix to github.com/canonical/go-tpm2/linux that ensures I/O system calls are retried on EINTR.
=> Bump github.com/canonical/go-tpm2 dependency to v1.3.0

crypt.go, crypt_test.go, internal/compattest/compattest_test.go, keydata.go, keydata_test.go, keyring.go, keyring_test.go, tpm2/export_test.go, tpm2/keydata_legacy.go, tpm2/keydata_v3_test.go, tpm2/platform_legacy.go, tpm2/platform_legacy_test.go, tpm2/platform_test.go, tpm2/policy.go, tpm2/policy_v0.go, tpm2/policy_v1.go, tpm2/policy_v3.go, tpm2/policy_v3_test.go, tpm2/seal.go, tpm2/seal_legacy.go, tpm2/seal_legacy_test.go, tpm2/seal_test.go, tpm2/unseal_legacy.go, tpm2/unseal_legacy_test.go, tpm2/update.go, tpm2/update_legacy.go, tpm2/update_test.go
First 2 commits taken from https://github.com/chrisccoulson/secboot/tree/keydata-format-improvements-v2 and rebased on top of recent master.
This adds the following changes:
1) Renaming AuxiliaryKey to PrimaryKey
2) adds a basic legacy behavior test to ensure correct behavior for the upcoming changes related to the new keydata format.
=> Keydata v3 auxiliary primary rename and legacy keydata test

crypt_test.go, export_test.go, keydata.go, keydata_file_test.go, keydata_legacy.go, keydata_legacy_test.go, keydata_luks_test.go, keydata_test.go, platform.go
Original commit: https://github.com/chrisccoulson/secboot/commit/87d9aa34d1d80d64ffe82f0a008693799d633cd9
I will split the commit above in 3 separate cascading PRs and add tests for it:
1. This one
2. https://github.com/snapcore/secboot/pull/270
3. https://github.com/snapcore/secboot/pull/271
=> [1/3] Keydata v3 platform API changes

argon2.go, crypt.go, crypt_test.go, internal/luks2/cryptsetup.go, internal/luks2/cryptsetup_test.go, internal/luksview/tokens_test.go, internal/luksview/view_test.go
We currently use a minimal Argon2i configuration for the main unlock
keyslots and then Argon2i benchmarked to 2s by default for recovery
keyslots. Note that the cryptsetup default now is Argon2id, but Argon2
is overkill in this context anyway.
For the main unlock keyslots, hardcode a minimal PBKDF2 configuration.
Also hardcode a PBKDF2 configuration for the recovery keyslots, but
use 600,000 iterations which is the current OWASP recommendations for
ordinary passphrases
(https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html).
This is still overkill for a 128bit recovery key, and if we implement a
256bit recovery key then we could justify using a minimal configuration
here as well. Note that systemd is using minimal PBKDF2 configurations
for both normal and …
=> use PBKDF2 for the LUKS2 keyslots

argon2.go, argon2_test.go, internal/argon2/argon2.go, internal/argon2/argon2_test.go, internal/testutil/kdf.go
The key length has a negligible effect on the execution time, so use
a fixed key length of 32 bytes for benchmarking.
Note that this keeps the keyLen argument to KDFOptions.deriveCostParams
as this is going to become an interface in a future PR, where the key
length will be used to select the default PBKDF2 hash.
=> argon2: use a fixed key length for benchmarking

argon2.go, argon2_test.go, crypt.go, crypt_test.go, export_test.go, internal/argon2/argon2.go, internal/testutil/argon2.go, keydata.go, keydata_legacy_test.go, keydata_test.go, tpm2/export_test.go, tpm2/platform_test.go, tpm2/seal.go
This renames the existing KDFOptions, KDFCostParams and KDF types to
Argon2Options, Argon2CostParams and Argon2KDF in preparation for
the introduction of PBKDF2 support for passphrases in another PR, which
will use a new options implementation. Both options implementations will
implement a new interface (KDFOptions).
As PBKDF2 won't be abstracted like Argon2 is because it doesn't use lots
of memory, also remove the kdf argument from functions that take them.
Instead, have a process wide Argon2KDF implementation, set by calling
SetArgon2KDF.
=> argon2: refactor API to prepare for PBKDF2 support for passphrases

plainkey/export_test.go, plainkey/keydata.go, plainkey/keydata_test.go, plainkey/plainkey_test.go, plainkey/platform.go, plainkey/platform_test.go
This platform provides a way to unlock an encrypted container using a
key recovered from unlocking another container, and is suitable when
access to one encrypted container implies access to another one.
The intention of this is to replace the existing mechanism for unlocking
the save partition in run mode with something that uses a proper keyslot.
Keys are protected with a "platform key" - this is the key that is
stored in the first encrypted container. For the intended use case,
this key is stored inside the data partition, and then loaded by
snap-bootstrap, which should call plainkey.SetPlatformKeys before
unlocking the save partition.
Although normally there will only be a single key supplied to
SetPlatformKeys, it supports setting multiple keys and then matching
a key data object to …
=> Add plainkey platform

bootscope/export_test.go, bootscope/keydata.go, bootscope/keydata_test.go, export_test.go, keydata.go, keydata_legacy.go, keydata_legacy_test.go, keydata_test.go
This addresses:
- keyDataLegacyTestBase not used from https://github.com/snapcore/secboot/pull/265#discussion_r1450626357
- use DecodeHexString from https://github.com/snapcore/secboot/pull/265#discussion_r1487572075
Also makes hashAlg public as it will be used in a follow-up PR which will slightly rework the mockPlatformKeyDataHandler to use GCM and associated data to check expected values.
=> Keydata testsuite minor refactors and improvements and hashAlg

efi/efi.go, efi/efi_test.go, efi/export_test.go, efi/fw_load_handler.go, efi/fw_load_handler_test.go, efi/grub_load_handler_test.go, efi/pcr_profile.go, efi/pcr_profile_test.go, efi/sdstub_policy.go, efi/shim_load_handler_test.go, efi/uc_uki_load_handler.go, efi/uc_uki_load_handler_test.go, tpm2/export_test.go, tpm2/snapmodel_policy.go, tpm2/snapmodel_policy_test.go
This replaces the separate calls to AddSystemdStubProfile and
tpm2.AddSnapModelProfile, which are now deprecated and will be
removed in a follow-up PR.
=> efi: add WithKernelConfigProfile option to AddPCRProfile

argon2.go, argon2_test.go, export_test.go, internal/argon2/argon2.go, internal/argon2/argon2_test.go, internal/testutil/argon2.go, keydata.go, keydata_test.go
Passphrase support currently hardcodes the use of argon2i, which is
the data-independent version of Argon2. Whilst this has better
side-channel resistance than data-dependent versions, it requires
more iterations to protect against time-memory tradeoff attacks.
Cryptsetup recently switch to argon2id by default for passphrase
hashing, which is the hybrid version that provides a good balance
between side-channel resistance and time-memory tradeoff.
This introduces support for selecting between the 2 versions for
passphrase support.
There are other versions of Argon2, such as the data-dependent version
which sacrifices side-channel resistance for better resistance against
time-memory tradeoff attacks, but this isn't supported by the argon2 go
package.
=> add support for the hybrid mode of Argon2 for passphrases

efi/fw_load_handler.go, efi/fw_load_handler_test.go
We copy the EV_SEPARATOR events from the firmware log because it can
be one of two valid values. But we should be aborting early if any of
these separators indicate that an error occurred in firmware rather
than continuing to build a profile.
=> efi: Don't create profiles with invalid separators

efi/fw_load_handler.go, efi/fw_load_handler_test.go, efi/internal/absolute.go, efi/internal/absolute_test.go, efi/internal/internal_test.go, go.mod, go.sum, internal/efitest/log.go
Some newer laptops are loading endpoint management applications that are
shipped with firmware, and these are being loaded as part of the OS-present
environment with the LoadImage API, resulting in them being measured to PCR4.
This currently causes us to mis-predict values for PCR4 because everything
after the separator (the pre-OS to OS-present transition) is assumed to
belong to the OS and gets dropped from the predicted measurements.
A future PR will provide support for detecting compatibility for FDE,
with an option for detecting and disallowing these firmware applications.
In most cases, they should be disabled (and it's possible to disable
Absolute from userspace on Dell laptops), but we should add support here
for specific, known endpoint management applications for any edge cases …
=> efi: PCR4: Add support for certain firmware applications loaded during OS-present

plainkey/export_test.go, plainkey/keydata.go, plainkey/keydata_test.go, plainkey/platform.go, plainkey/platform_test.go
"Platform" is a bit overloaded in this package, eg, there is a
`secboot.PlatformKeyData` type already and EFI has a "Platform Key" as
well.
=> plainkey: rename platform key to protector key

efi/preinstall/check_virt.go, efi/preinstall/check_virt_test.go, efi/preinstall/export_test.go, efi/preinstall/preinstall_test.go
If a container environment is detected, this always return an error.
Detecting a VM returns a value which will be interpreted by the caller
(`RunChecks`) and will also return an error unless a flag is specified
by snapd to suppress this, in which case the subsequent firmware
protection tests will be skipped because these don't make sense in
virtualized environments.
=> preinstall: Add checks for virtualization mode

efi/preinstall/check_tpm.go, efi/preinstall/check_tpm_test.go, efi/preinstall/errors.go, efi/preinstall/export_test.go, efi/preinstall/preinstall_test.go
This adds checks that we have a TPM2 device, that it is enabled, that it
is not in DA lockout mode, that it is not already owned by having an
authorization value for any of the 3 hierarchies we can use, that it is
a PC-Client device, and that it has enough spare NV counter indexes to
supprt PCR policy revocation. If the checks succeed, it returns a
`tpm2.TPMContext` that will be consumed by `RunChecks` for other tests, and
which will have to be closed later on.
=> preinstall: Add checks for TPM2 device

efi/fw_load_handler.go, efi/fw_load_handler_test.go, efi/preinstall/check_fw_protections.go, efi/preinstall/check_fw_protections_test.go, go.mod, go.sum, internal/efitest/log.go
github.com/canonical/tcglog-parser defined its own types for PCR indides
and digests, which resulted in a bunch of pointless conversions between
these and go-tpm2 equivalent types in packages that depended on both of
these, despite the fact that tcglog-parser already depends on go-tpm2.
I've removed the tcglog-parser type definitions in master and updated it
here which allows us to remove a fair few type conversions.
=> various: update github.com/canonical/tcglog-parser

argon2.go, argon2_test.go, internal/argon2/argon2.go, internal/argon2/argon2_test.go
We're currently wrapping x/crypto/argon2 which panics on some invalid
arguments. Instead, move the checking of these arguments in order to
avoid some panics.
=> internal/argon2: return errors

efi/fw_load_handler_test.go, efi/pcr_profile_test.go, efi/preinstall/check_tcglog.go, efi/preinstall/check_tcglog_test.go, efi/preinstall/errors.go, efi/preinstall/export_test.go, go.mod, go.sum, internal/efi/tcg_pcrs.go, internal/efitest/log.go
This adds a function that verifies that the TCG log is well formed and
is consistent with the TPM's PCR values for at least one supported PCR
bank. On success, it returns the best PCR bank to use and the startup
locality, and any errors that occurred for non-mandatory PCRs. A PCR
might not be mandatory because we don't have a way to generate profiles
for it, or because the input flags to `RunChecks` marked it as optional.
The startup locality is used later on with the discrete TPM indication
returned from the earlier TPM check to customize the PCR profile.
It performs some other tests, notably that:
- the TCG log contains a sequence of expected phases.
- the TCG defined PCRs contain a EV_SEPARATOR event between the pre-OS
and OS-present environment (although the one in PCR7 separates …
=> preinstall: Add initial checks for TCG log consistency with PCR values

efi/preinstall/check_pcr2.go, efi/preinstall/check_pcr2_test.go, efi/preinstall/export_test.go
This adds a minimal check for PCR 2 which determines whether any
code from value-added-retailer components is executing or not. This
will be used by `RunChecks` because there will be an option to reject
systems that include code from value-added-retailer components.
As `efi.WithDriversAndAppsProfile` just copies events from the log and
does no prediction for this PCR, this function doesn't do any more
extensive testing, such as ensuring that the PCR only contains events
of the expected type, the event data for each event is of an expected
type, and for events where the digest is a tagged hash of the event
data, that the digest is consistent with the event data.
=> preinstall: Add minimal checks for PCR 2

efi/preinstall/check_pcr4.go, efi/preinstall/check_pcr4_test.go, efi/preinstall/export_test.go, go.mod, go.sum, internal/efitest/log.go
This adds checks some checks for PCR4.
The caller supplies a `context.Context` to which an EFI variable backend
is attached, a `internal_efi.HostEnvironment` implementation, a TCG log, a
PCR digest algorithm (the optimum for this is computed earlier by
another function that does a more general check of the TCG log) and a
list of boot images related to the current boot. These are used to
verify the digests in the `EV_EFI_BOOT_SERVICES_APPLICATION` events.
It reads the `BootCurrent` EFI variable and matches this to the
`EFI_LOAD_OPTION` associated with the current boot from the TCG log - it
uses the log as `BootXXXX` EFI variables can updated at runtime and might
be out of date when this code runs.
In the pre-OS environment, it checks that the log only contains either
a single …
=> preinstall: Add checks for PCR4

crypt.go, crypt_test.go, export_test.go
Snapd has used path of the for
/dev/disk/by-partuuid/deadbeef-dead-dead-dead-deaddeafbeef to activate LUKS2 containers.
`by-partuuid` does not make much sense because it uselessly assumes that it is a partition, where in the future we might have to do something else. It also makes the resolution of the name more complex. We have to resolve the UUID of the LUKS2 header, then query udev for a disk with that UUID, and then ask for the uuid of the partition.
Instead we should either, use a path like
`/dev/disk/by-uuid/deadbeef-dead-dead-dead-deaddeafbeef`, or `UUID=deadbeef-dead-dead-dead-deaddeafbeef`, where the UUID is the one of the LUKS2 header. Or eventually if we do not like symlinks, use `/dev/nodeN`.
Unfortunately, because snap-bootstrap in the initrd might not match exactly, at this …
=> crypt: optionally registers keying entries with legacy paths

efi/preinstall/check_tpm.go, efi/preinstall/check_tpm_test.go, efi/preinstall/errors.go
The `RunChecks` API will support being executed post-install even
though it's primarily a pre-install API. A use case for this is re-running
it as part of the post-recovery repair process. Not all tests makes sense
post-install, unless a motherboard (and TPM) change was the reason for
recovery, and so are skipped.
We were already skipping the lockout hierarchy auth value test during
post-install because this doesn't make sense, but also skip similar
tests for other hierarchies and also skip the lockout checkout and the
test for sufficient number of NV counters.
=> preinstall: move some extra TPM tests to only run during pre-install

tpm2/export_test.go, tpm2/key_sealer.go, tpm2/key_sealer_test.go, tpm2/keydata.go, tpm2/platform_test.go, tpm2/policy.go, tpm2/policy_test.go, tpm2/policy_v0.go, tpm2/policy_v0_test.go, tpm2/policy_v1.go, tpm2/policy_v1_test.go, tpm2/policy_v3.go, tpm2/policy_v3_test.go, tpm2/seal.go, tpm2/seal_test.go, tpm2/unseal.go
By default, all TPM2 keys are protected by the TPM's dictionary attack
protection logic. Given that the user auth mode is immutable, we should
take advantage of this to create keys that require no user auth with the
noDA attribute, so that they aren't protected by the TPM's dictionary
attack protection logic. This means that these keys will still be
recoverable, even if the TPM is in lockout mode.
=> tpm2: Create TPM2 keys with noDA attribute if no user auth is required

efi/preinstall/check_tcglog.go, efi/preinstall/check_tcglog_test.go, efi/preinstall/checks.go, efi/preinstall/checks_test.go, efi/preinstall/errors.go
Whilst this has no consequence for FDE because we seal against a good
bank, it breaks measured boot as required by remote verifiers, as an
empty PCR bank provides a means for an adversary to spoof any host
platform of their choosing.
We reject systems with empty PCR banks by default, but with an opt-in to
permit it. Permitting it is fine for now, but when we get to the point of a
fully verified and attestable runtime in the future, this will not be permitted.
We will need to take some action here, such as capping PCRs 0-7 with an
`EV_SEPARATOR` type event that indicates an error occurred in those banks.
Whilst an empty PCR bank is considered a firmware bug and we shouldn't be
seeing it on newer devices, it's not that uncommon to see this on devices from
the era when TPM2 devices started …
=> preinstall: Add explicit checks for empty PCR banks

tpm2/policy_test.go, tpm2/seal_test.go
The vast majority of tests were performed with the role field empty, which isn't going to be the typical situation.
=> tpm2: Add more tests with the role field populated

go.mod, go.sum, internal/testutil/argon2.go
The previous import was github.com/canonical/go-sp800.108-kdf. I've since moved it to github.com/canonical/go-kbkdf and renamed the module accordingly, following the naming convention for this KDF on openssl.
The package is largely the same, just with the HMAC implementation of the PRF split into its own sub-package. This package has global variables for pre-defined PRFs for each supported SHA2 algorithm.
=> internal/testutil: Update import for KBKDF

internal/efi/default_env.go, internal/efi/default_env_test.go, internal/efi/env.go, internal/efi/export_test.go
Other code in secboot makes use of this recently introduced package,
so the code in internal/efi should use it too.
=> internal/efi: Use internal/tpm2_device package

efi/preinstall/check_tcglog.go, efi/preinstall/check_tcglog_test.go, efi/preinstall/checks.go, efi/preinstall/checks_test.go, efi/preinstall/errors.go, efi/preinstall/export_test.go
The new error captures empty PCRs for all active banks in which they exist as opposed to terminating early.
Note that I needed a 3rd algorithm to properly test the multiple empty PCR bank case whilst still having one good PCR bank. Given that the simulator doesn't have SHA-512 enabled, this needed to be SHA1. This means that this PR also adds support for selecting SHA1 as a PCR digest, but it is hidden behind a flag (PermitWeakPCRBanks).
=> preinstall: Rename EmptyPCRBankError to EmptyPCRBanksError

crypt.go, crypt_test.go
Factory reset requires renaming of keyslots. Unfortunately `cryptsetup` on UC 20 and UC 22 do not support `--token-replace`. So we need a way rename without that feature.
=> crypt.go: allow renaming keys without cryptsetup features

crypt_test.go, keydata.go, keydata_file_test.go, keydata_luks_test.go, keydata_test.go, tpm2/platform_test.go, tpm2/update_test.go
PR #361 addressed the issue that most tpm2 tests were being performed with an empty role, which isn't realistic. It turns out that I missed a few places, particularly in some of the platform tests, that if I had fixed in the previous PR, would have noticed that the role parameter isn't being passed through the platform interface (this would get picked up when changing a password because key validation would fail).
This addresses this, and fixes tests in the top-level package to catch it as well.
Note that I'm using the same value in most tests - my normal approach to unit testing is to test each input with at least more than one value, but the tests in the top-level secboot package and the tpm2 sub-package are getting a bit complicated with a lot of inconsistencies in their approach to …
=> Fix plumbing of the role via the PlatformKeyDataHandler interface

bootscope/keydata_test.go, hooks/platform.go, internal/tpm2test/suites.go, keydata.go, keydata_test.go, plainkey/platform.go, platform.go, tpm2/platform.go, tpm2/platform_legacy.go, tpm2/platform_legacy_test.go, tpm2/platform_test.go, tpm2/seal.go, tpm2/seal_test.go, tpm2/tpm_test.go, tpm2/update_test.go
When using `NewTPMPassphraseProtectedKey`, it is passed an already open
connection. But the core secboot package calls back into the platform
handler to set the user auth value, which opens a second connection.
When using the direct device (/dev/tpm0), this doesn't work.
This updates the test suite to make sure that this scenario is caught
and results in an error. It also fixes the problem by providing a way to
pass the open TPM connection to the singleton tpm2 platform handler
via a new field on the `secboot.KeyWithPassphraseParams` struct which
can be set to any value and is passed to the `ChangeAuthKey` implementation
when setting the initial auth value. The tpm2 platform handler
implementation uses this connection if passed rather than trying to open a
new connection. If the …
=> tpm2: Avoid attempting to open duplicate TPM connections

efi/preinstall/checks_test.go
The unit tests were supplying expected flags but the tests were not
actually testing that the returned value matches.
=> efi/preinstall: Add missing test for expected CheckResultFlags

efi/preinstall/check_tcglog.go
As SHA1 is a PCR algorithm that this package can choose (with the `PermitWeakPCRBanks` flag enabled), this package should include the `crypto/sha1` package so that the behaviour is consistent with other algorithms where we already include those packages for supported algorithms.
=> efi/preinstall: Include crypto/sha1 package

bootscope/keydata_test.go, hooks/platform.go, keydata.go, keydata_legacy_test.go, keydata_test.go, plainkey/platform.go, platform.go, platform_test.go, tpm2/platform.go, tpm2/platform_legacy.go
When adding features to key metadata, we need to be sure that we have kernels that contain a snap-bootstrap based on a new enough version of secboot before those features can be used. Given that other requirements mean that we will be passing information from early boot to snapd, we may as well pass information about the secboot packages compiled into snap-bootstrap as part of that information.
In order to do this, I've added a way for each platform that registers a handler to be able to specify a set of flags. Each platform has 40-bits which they can use however they choose. The remaining 24-bits may be used for common flags in the future (eg, we could have a common flag to allow a platform to indicate that it supports user auth rather than doing what we do today - we just call into the …
=> Add a flags argument associated with registered PlatformKeyDataHandlers

.github/workflows/test.yaml
I'm in the process of updating the TPM simulator to the one based on
v1.83 of the reference library. Although the default reference build
still keeps SHA1 as a supported algorithm, it only enables the SHA256
and SHA384 PCR banks by default, which is likely to break some tests
where we assume that we have SHA1 banks (as we are able to with the
version of the simulator we've been using for the previous ~2 years).
In order to make the transition smoother, I've copied the previous
version of the TPM simulator to stable, and this updates the workflow
to pull in the simulator from latest/stable. I'll probably need to do
some work in secboot in order to get the tests working in the absence
of the SHA1 bank by default, after which, the new simulator based on
v1.83 of the reference library can be …
=> tests: Use the stable channel for the TPM simulator

efi/preinstall/check_tpm.go, efi/preinstall/check_tpm_test.go, efi/preinstall/errors.go, go.mod, go.sum
This adds 2 more TPM tests:
- That no hierarchy has an authorization policy set.
- That the TPM is not in failure mode.
It also moves the lockout check until after we've checked that all of
the hierarchies are unowned. This is because it simplifies potential
options for rectifying this failure later.
Also, the hierarchy ownership checks are rolled into a new error
(TPM2OwnedHierarchiesError) which can capture multiple hierarchies in a
single error, which is a bit more useful.
=> efi/preinstall: Add some more TPM tests

auth_requestor_systemd.go, auth_requestor_systemd_test.go
text/template brings 4MB into snap-bootstrap. That makes some customers not able to update their kernels.
=> auth_requestor_systemd.go: do not use text/template

efi/preinstall/check_tcglog.go
This doesn't have any effect on the declared enum constants, hence there
are no unit test changes. It just fixes a mistake in the way that the
constants are declared, and makes them consistent with others in this
repository.
=> preinstall: Fix declaration of tcglogPhase enum constants

efi/preinstall/check_fw_protections_amd64.go, efi/preinstall/check_tcglog.go, efi/preinstall/check_tcglog_test.go, efi/preinstall/checks.go, efi/preinstall/checks_test.go, efi/preinstall/errors.go
NoSuitablePCRAlgorithm error had 2 fields from which to obtain errors -
a field for errors that affect an entire PCR bank, and a field for
errors that affect a single PCR in a bank.
Simplify this by having a single field for all errors, which are stored
in a map that is keyed by the PCR bank. PCR-specific errors are added to
this field wrapped in the relevant PCR-specific error type instead, so
that the PCR-specific errors are returned for any errors affecting a PCR,
regardless of whether that error occurs during or after the bank
selection.
=> preinstall: Simplify NoSuitablePCRAlgorithmError

efi/preinstall/checks.go, efi/preinstall/checks_test.go, efi/preinstall/errors.go
PlatformFirmwareProtectionError is returned not just for errors that are
related to firmware security, but in the case where the currently running
kernel doesn't have a IOMMU. Renaming it to HostSecurityError makes
a bit more sense, and it's shorter.
=> preinstall: Rename PlatformFirmwareProtectionError to HostSecurityError

efi/preinstall/check_fw_protections_amd64.go, efi/preinstall/check_fw_protections_amd64_test.go, efi/preinstall/check_fw_protections_intel.go, efi/preinstall/check_fw_protections_intel_test.go
The check for CPU silicon-level debugging is testing the contents of a
MSR that is Intel specific. When we have checks for AMD CPUs, this test
won't apply to that (or, we may need an AMD-specific test).
=> preinstall: only check for CPU debugging on Intel

efi/preinstall/check_fw_protections.go, efi/preinstall/check_fw_protections_amd64.go, efi/preinstall/check_fw_protections_amd64_test.go, efi/preinstall/check_fw_protections_test.go, efi/preinstall/check_tcglog.go, efi/preinstall/check_tcglog_test.go, efi/preinstall/check_tpm.go, efi/preinstall/check_tpm_test.go, efi/preinstall/checks.go, efi/preinstall/checks_test.go, efi/preinstall/errors.go
RunChecks returns some errors immediately, whilst other errors are
grouped together and returned wrapped by RunChecksErrors at the end of
the function. However, there are some inconsistencies with the way this
happens. This PR attempts to clean that up. RunChecks will return errors
immediately in the following cases:
- Testing cannot continue with the error (eg, a PCR bank cannot be
selected, the TPM is in failure more etc).
- The error cannot be rectified (eg, misconfigured BootGuard, not having
a TPM2 device etc).
Other errors shouldn't immediately halt testing and should be gathered
to be returned together on completion of RunChecks.
=> preinstall: Be consistent about which errors to return immediately from RunChecks

efi/preinstall/check_fw_protections_amd64_test.go, efi/preinstall/check_tcglog.go, efi/preinstall/check_tpm.go, efi/preinstall/check_tpm_test.go, efi/preinstall/checks.go, efi/preinstall/checks_test.go, efi/preinstall/errors.go, efi/preinstall/errors_test.go, efi/preinstall/export_test.go, efi/preinstall/result.go, efi/preinstall/result_test.go
There are currently 2 error types that wrap multiple errors:
RunChecksErrors and joinError which is used internally. The additional
API that will come in the next PR also wants a way to wrap multiple
errors, so this removes RunChecksErrors in favour of a single type which
isn't public, and a public interface.
=> preinstall: use a single type for wrapping multiple errors

efi/preinstall/check_fw_protections_amd64.go, efi/preinstall/check_fw_protections_amd64_test.go, efi/preinstall/check_fw_protections_intel.go, efi/preinstall/check_tpm.go, efi/preinstall/check_tpm_amd64.go, efi/preinstall/check_tpm_amd64_test.go, efi/preinstall/check_tpm_intel.go, efi/preinstall/check_tpm_intel_test.go, efi/preinstall/check_tpm_null.go, efi/preinstall/check_tpm_test.go, efi/preinstall/checks.go, efi/preinstall/checks_context_test.go, efi/preinstall/export_test.go, efi/preinstall/util_amd64.go, efi/preinstall/util_amd64_test.go
The TPM discreteness check relies on the BootGuard status MSR on Intel.
Move this check until after the point where we know that BootGuard is
configured properly.
=> preinstall: Move TPM discreteness check

efi/preinstall/checks.go, efi/preinstall/checks_context.go, efi/preinstall/checks_context_test.go, efi/preinstall/checks_test.go, efi/preinstall/errors.go
Every other flag works in reverse and has to be specified in order to
permit an error condition as ok. Reverse the logic in these flags so
that they also have to be specified in order to permit support for
specific PCRs to be missing.
=> preinstall: Reverse the logic of the *SupportRequired flags

crypt.go, crypt_test.go, internal/luks2/cryptsetup.go, internal/luks2/cryptsetup_test.go, internal/luks2/luks2test/luks2test.go
Also remove internal API luks2test.CheckLUKS2Passphrase and adjust existing internal users of that API to use the new one.
=> Add new public API `TestLUKS2ContainerKey` for testing LUKS2 container keys

container.go, container_test.go, export_test.go, keydata.go, platform.go, storage.go, storage_test.go
This adds a new `StorageContainerBackend` interface to permit the core
secboot package to communicate with a registered package that handles
encrypted containers and keyslots (such as luks2) so that future code
in secboot will be agnostic to the type of storage container.
The `StorageContainerBackend` provides a way to probe a backend with a path
so that it can return a `StorageContainer` if appropriate. It also
provides a way to activate and deactivate an encrypted `StorageContainer`.
The `StorageContainer` provides a way to open a `StorageContainerReader`,
permitting code in secboot or outside of secboot to perform read only
operations on keyslots.
Eventually, the `StorageContainer` will provide a way to open a
`StorageContainerReadWriter`, permitting code in secboot or outside to …
=> Add initial StorageContainer abstractions

efi/preinstall/checks.go, efi/preinstall/checks_context_test.go, efi/preinstall/checks_test.go
In the event that a PCR has an unexpected value, don't then skip the
later PCR-specific tests that can detect whether system-preparation
applications or value-added-retailer drivers are being executed.
=> preinstall: return some PCR errors in more circumstances

efi/preinstall/check_tpm.go, efi/preinstall/check_tpm_test.go, efi/preinstall/load_option_util_test.go, go.mod, go.sum, internal/efi/absolute_test.go, internal/efitest/log.go
This also updates the go-tpm2 version to pull in a fix that would have
meant the existing secboot tests would have caught this bug.
=> preinstall: Fix an issue with the TPM connection being closed prematurely

efi/preinstall/check_tpm.go, efi/preinstall/check_tpm_test.go, efi/preinstall/checks_context.go, efi/preinstall/checks_context_test.go, efi/preinstall/error_kinds.go, efi/preinstall/errors.go, efi/preinstall/tpm_util.go, efi/preinstall/tpm_util_test.go
There is already a test that the dictionary attack protection hasn't
been triggered, which makes DA protected resources unavailable - this
results in a `ErrTPMLockout` error and a `ErrorKindTPMDeviceLockout` error
kind.
This adds another test that the actual lockout hierarchy is available,
which has its own dictionary attack protection. However, there is no
direct test for this other than to try authenticating the lockout
hierarchy, and only a single failure will trigger a lockout. To do this,
we execute `TPM2_DictionaryAttackLockReset` if the lockout hierarchy has
no authorization value set. If we authorize it with the empty value,
there is no valid reason for authorization to fail. If the TPM returns a
`TPM_RC_LOCKOUT` warning, then we return a separate error for this - …
=> efi/preinstall: Add a test that the lockout hierarchy is enabled

efi/preinstall/checks.go
I landed PR412 without noticing that the tests are failing on go 1.18,
but passing with a newer go. It looks like it's because the test of each
error value returned from `checkHostSecurity` is being performed on the
wrong error value - it works with newer go versions because it has
native support for `[]error` with `errors.Is`.
=> preinstall: Fix PR412 on go1.18

efi/preinstall/check_host_security_intel.go, efi/preinstall/check_host_security_intel_test.go, efi/preinstall/check_tpm_intel.go, efi/preinstall/check_tpm_intel_test.go, efi/preinstall/checks_context.go, efi/preinstall/checks_context_test.go, efi/preinstall/checks_test.go, efi/preinstall/errors.go, efi/preinstall/errors_test.go, internal/efitest/hostenv.go
Some tests rely on kernel APIs that are currently shipped in modules as
opposed to being shipped in the main kernel image. The required modules
may not be loaded in all circumstances.
Whilst I don't think that secboot, as a dependency of snapd, should be directly
loading kernel modules, there needs to be a mechanism to tell snapd which
kernel modules are required in order for the tests to run successfully. The
required kernel modules are an implementation detail of secboot and may be
architecture / platform dependent as well, so snapd shouldn't have a list of
kernel modules to load. Instead, if a feature that requires a kernel module
cannot complete because it appears that the kernel module isn't loaded,
secboot will return a `MissingKernelModuleError` which describes the module
that …
=> efi/preinstall: Provide a way to indicate that a required kernel module is missing

container.go, container_test.go, keydata.go, luks2/api.go, luks2/backend.go, luks2/backend_test.go, luks2/container.go, luks2/container_test.go, luks2/dm_helper.go, luks2/dm_helper_test.go, luks2/export_test.go, luks2/keyslot.go, luks2/keyslot_info.go, luks2/luks2_test.go, luks2/reader.go, luks2/reader_test.go, storage.go, storage_test.go
This provides an initial LUKS2 implementation of
`StorageContainerBackend`, with read-only, activate and deactivate support
for now, and the initial implementation largely just wrapping around the
existing secboot APIs.
Plans for the future for this package:
- Adding an implementation of `StorageContainerReadWriter` once it's
defined in secboot.
- Introduction of locking to serialize access to implementations of
`StorageContainerReader` and `StorageContainerReadWriter`.
- Moving LUKS2 functionality from the code secboot package and
`internal/luksview` into this package, and deleting the existing code.
=> luks2: Add initial LUKS2 StorageContainerBackend

efi/preinstall/check_host_security.go, efi/preinstall/check_host_security_test.go, efi/preinstall/check_pcr7_test.go, efi/preinstall/checks_context_test.go, efi/preinstall/checks_test.go
If secure boot is disabled and the `SbatLevel` UEFI variable didn't exist
when shim executed, there will be no `EV_EFI_VARIABLE_AUTHORITY` events in
PCR7. At least one of these is required by
`checkSecureBootPolicyPCRForDegradedSettings` in order for the function to
return rather than the loop terminating and then hitting a panic at the
end of the function.
=> efi/preinstall: Fix a panic that can happen when secure boot is disabled

.github/workflows/test.yaml, efi/preinstall/check_host_security.go, efi/preinstall/check_host_security_test.go, efi/preinstall/check_pcr7_test.go, efi/preinstall/checks_context_test.go, efi/preinstall/checks_test.go
Incorporate fix pull/461 into snapd specific branch for snapd release 2.71.1
- Snapd 2.71 specifies go.mod specifies: github.com/snapcore/secboot v0.0.0-20250723142039-3e181c8edf0f
- This points to commit: https://github.com/canonical/secboot/pull/442
- To enable release 2.71.1 we need to cherry pick fix: https://github.com/canonical/secboot/pull/461 (2 commits)
=> for snapd release 2.71.1
